### ISSUE TITLE
2019 sets update plz

### ISSUE THREAD

**Issue by syvy** [xsilium/MTG-Printable-Labels#5]
war of the spark, core2020, modern horizons, commander 2019, throne of eldraine

**Comment by davidfischer** [comment]
If you're interested, I created a [script](https://github.com/davidfischer/mtg-printable-set-label-generator) that generates similar labels from the Scryfall API. It's updated through Theros Beyond Death although when new sets come out, updating for new sets should be as easy as re-running it. I used labels from this repo for a while and they were great. It made me really want something I could update myself easily without waiting on other people.

**Comment by xsilium** [comment]
Updated this morning. Enjoy!
