### ISSUE TITLE
Incorrect set symbol for Signature Spellbook: Chandra

### ISSUE THREAD

**Issue by jmcsmith** [xsilium/MTG-Printable-Labels#9]
![image](https://user-images.githubusercontent.com/16355877/91665659-3f51be00-eac5-11ea-99b7-601b6e76ad42.jpeg)

**Comment by xsilium** [comment]
Thank you for letting me know about this issue. I updated this file before a lot of 2020 was finalised, but I will work to resolve these issues today.
